apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/nei7/k3s-cluster.git
    targetRevision: HEAD
    path: argocd/blog
  destination:
    server: https://kubernetes.default.svc
    namespace: blog
  syncPolicy:
    syncOptions:
      - "CreateNamespace=true"

    automated:
      selfHeal: true
      prune: true
