apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mysecret
  data:
    - secretKey: password
      remoteRef:
        key: secret1
        property: password
    - secretKey: user
      remoteRef:
        key: secret1
        property: user
