apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: inlets-accesskey-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: inlets-access-key
  data:
    - secretKey: inlets-access-key
      remoteRef:
        key: inlets
        property: access-key
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue

