apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: inlets-license-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: inlets-license
  data:
    - secretKey: license
      remoteRef:
        key: inlets
        property: license
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue

