- name: Perequisites
  hosts: all

  tasks:
    - name: Enable cgroup via boot commandline
      become: true
      ansible.builtin.lineinfile:
        path: /boot/firmware/cmdline.txt
        backrefs: true
        regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
        line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
      notify: Reboot Pi

  handlers:
    - name: Reboot Pi
      ansible.builtin.reboot:
        post_reboot_delay: 10
        reboot_timeout: 60
