configs:
  params:
    server.insecure: true
  cm:
    statusbadge.enabled: "true"
    # Adding Applications health check
    resource.customizations.health.argoproj.io_Application: |
      hs = {}
      hs.status = "Progressing"
      hs.message = ""
      if obj.status ~= nil then
        if obj.status.health ~= nil then
          hs.status = obj.status.health.status
          if obj.status.health.message ~= nil then
            hs.message = obj.status.health.message
          end
        end
      end
      return hs
    # Enabling Helm chart rendering with Kustomize
    kustomize.buildOptions: --enable-helm

server:
  # Ingress Resource.
  ingress:
    ## Enable creation of ingress resource
    enabled: true
    ## Add ingressClassName to the Ingress
    ingressClassName: traefik
    # ingress host
    hosts:
      - argocd.fszarek.com
    ## TLS Secret Name
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.fszarek.com
    ## Default ingress path
    paths:
      - /