apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: blog-externalsecret
  namespace: blog
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: blog-env
  dataFrom:
    - key: blog
