{{- if .Values.acme.dns01.cloudflare.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-key
  data:
  - secretKey: CLOUDFLARE_SECRET
    remoteRef:
      key: certmanager/cloudflare
      property: cloudflare-api-key
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
{{- end }}