# Prometheus servicemonitor configuration
serviceMonitor:
  enable: true
  release: monitoring

longhorn:
  defaultSettings:
    defaultDataPath: "/storage"
    # Backup S3 configuration
  # Ingress Resource. Longhorn dashboard.
  ingress:
    ## Enable creation of ingress resource
    enabled: true

    host: longhorn.fszarek.me


    tls: true


    tlsSecret: longhorn-tls

    path: /


    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-issuer
      cert-manager.io/common-name: longhorn.fszarek.me
      ingress.kubernetes.io/auth-type: "basic"
      ingress.kubernetes.io/auth-secret: traefik/basic-auth-secret