# Prometheus servicemonitor configuration
serviceMonitor:
  enable: true
  release: monitoring

#####################
# longhorn subchart
#####################

longhorn:
  defaultSettings:
    defaultDataPath: "/storage"
    # Backup S3 configuration
  # Ingress Resource. Longhorn dashboard.
  ingress:
    ## Enable creation of ingress resource
    enabled: true
    ## Add ingressClassName to the Ingress
    # ingress
    host: longhorn.fszarek.me

    ## Set this to true in order to enable TLS on the ingress record
    tls: true

    ## TLS Secret Name
    tlsSecret: longhorn-tls

    ## Default ingress path
    path: /

    ## Ingress annotations
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-issuer
      cert-manager.io/common-name: longhorn.fszarek.me
